### PR TITLE
update for 0.10

### PR DESCRIPTION
**Pull request by goodmind**

### CODE REVIEW

**Comment by goodmind** [comment]
@fluffynukeit can you update on bower?

**Comment by fluffynukeit** [comment]
I'm not sure what you mean.  If it's something easy for me to do, I'd be happy to help out.  However, I haven't touched this repo in a long time and will not be actively maintaining it in the future.  I'm ok with passing it off to another maintainer.

**Comment by goodmind** [comment]
@fluffynukeit i mean create release tag on github

**Comment by fluffynukeit** [comment]
Ok do you care what version or just do v0.1.2?

**Comment by goodmind** [comment]
@fluffynukeit just do it 👍

**Comment by fluffynukeit** [comment]
Ok done.

**Pull request merged**
