### PR TITLE
Update for latest purescript

### PR DESCRIPTION
**Pull request by clayrat**

### CODE REVIEW

**Comment by fluffynukeit** [comment]
Thanks for the PR.  I'm not very involved in PS much these days.  If you are interested in taking over this repo, let me know.

**Comment by clayrat** [comment]
The reason for this PR is that I wanted to use the purescript-dygraphs, and ended up updating both it and this one. I'll submit the updates for dygraphs too, but I am unsure if I'll be actively using/maintaining either of them. I think the official PS position on unmaintained but useful libs was to transfer them to purescript-contrib...

**Comment by clayrat** [comment]
Speaking of updating purescript-dygraphs: could you please tag the latest commit as 0.1.1 or something similar, so that I can fetch the updated dependency with Bower?

**Comment by fluffynukeit** [comment]
Should be done now.

**Comment by clayrat** [comment]
Hm, can't see it in https://github.com/fluffynukeit/purescript-foreign-options/releases, did you push?

**Comment by clayrat** [comment]
Oh, I'm sorry for being unclear! I meant that I need a tagged latest commit of this repo, `purescript-foreign-options`. This way, in bower dependencies for purescript-dygraphs I could refer to `"purescript-foreign-options":"latest"` and not have to hardcode a specific commit code. Sorry again for this trouble.

**Comment by fluffynukeit** [comment]
Ok the v0.1.1 number makes more sense to me now.  Should be tagged.  I tagged it directly in the github interface so it should already be pushed.

**Pull request merged**
